export default {
  GET_NEARBY_PRODUCTS: 'GET_NEARBY_PRODUCTS',
  GET_NEARBY_PRODUCTS_SUCCESS: 'GET_NEARBY_PRODUCTS_SUCCESS',
  GET_NEARBY_PRODUCTS_FAIL: 'GET_NEARBY_PRODUCTS_FAIL',
  GET_PRODUCT: 'GET_PRODUCT',
  GET_PRODUCT_SUCCESS: 'GET_PRODUCT_SUCCESS',
  GET_PRODUCT_FAIL: 'GET_PRODUCT_FAIL',
};
