export default {
  GET_INPUT: 'GET_INPUT',
  GET_CURRENT_LOCATION: 'GET_CURRENT_LOCATION',
  GET_CURRENT_LOCATION_SUCCESS: 'GET_CURRENT_LOCATION_SUCCESS',
  GET_CURRENT_LOCATION_FAIL: 'GET_CURRENT_LOCATION_FAIL',
};
